name: 'redsox_dbt'
version: '1.0.0'

profile: 'redsox_dbt'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  redsox_dbt:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
